apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: udpmirrors.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - port
                - buffer-size
              properties:
                port:
                  type: integer
                  minimum: 1
                  maximum: 65535
                buffer-size:
                  type: integer
                  minimum: 1
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: udpmirrors
    singular: udpmirror
    kind: UDPMirror
    shortNames:
      - udpm
